export enum Enum {
    CALCULATE_TAX_REQUEST = "CALCULATE_TAX_REQUEST",
    CALCULATE_TAX_SUCCESS = "CALCULATE_TAX_SUCCESS",
    CALCULATE_TAX_ERROR = "CALCULATE_TAX_ERROR",
    CALCULATE_STATE_UPDATE_SUCCESS = "CALCULATE_STATE_UPDATE_SUCCESS"
}
